### ISSUE TITLE
can use in WORKSPACE?

### ISSUE THREAD

**Issue by laichunhui** [cgrindel/rules_swift_package_manager#1047]
My main project uses an old WORKSPACE. Can I use BUILD.bazel and packages to add third-party libraries in submodules, and then import them into the workspace? Similar to the usage of vapor in the example, except that MODULE.bazel becomes WORKSPACE.

**Comment by cgrindel** [comment]
> to add third-party libraries in submodules,

I don't quite follow the layout that you are trying to achieve. However, if you see the layout in one of the examples, it should work for both legacy and bzlmod workspaces.

**Comment by laichunhui** [comment]
> > to add third-party libraries in submodules,
> 
> I don't quite follow the layout that you are trying to achieve. However, if you see the layout in one of the examples, it should work for both legacy and bzlmod workspaces.

I am developing a secondary project based on telegram, but it has so many submodules that I cannot migrate them to Bzlmod for the moment.

**Comment by cgrindel** [comment]
Feel free to re-open this issue or file a new one, if you run into any issues.
