### ISSUE TITLE
Support for `package` access modifier

### ISSUE THREAD

**Issue by watt** [cgrindel/rules_swift_package_manager#1057]
[SE-0386](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md) introduced the `package` access level. Packages using this require a `-package-name` argument to the compiler, which `rules_swift` rules [support via a `package_name` argument](https://github.com/bazelbuild/rules_swift/blob/master/doc/rules.md).

SE-0386 says this about the package name:

> The build system should make a best effort to ensure that package names are unique. The Swift Package Manager already has a concept of a package identity string for every package. This string is verified to be unique, and it already works as a package name, so SwiftPM will pass it down automatically. Other build systems such as Bazel may need to introduce a new build setting for a package name.

Since RSPM translates rules from SwiftPM, I think using the SwiftPM package name from `Package.swift` directly is the most obvious thing to do here. It should be fairly straightforward to copy this to the `package_name` arg when generating swift rules.

**Comment by brentleyjones** [comment]
That name probably isn’t unique enough if we consider that non-**rules_swift_package_manager** targets can also set a `package_name`. It probably also needs a rspm prefix/suffix.

I agree with the feature request though.

**Comment by cgrindel** [comment]
What if we used the repo name as the package name? For example, if the package identifier is `foo-bar`, the repo name would be `swiftpkg_foo_bar`. Would that be sufficient?

**Comment by brentleyjones** [comment]
I would still want a `.rspm` suffix. Just to prevent collisions more. But yeah that works.
