### ISSUE TITLE
Unable to determine link type for GoogleMaps iOS SDK

### ISSUE THREAD

**Issue by stephanecopin** [cgrindel/rules_swift_package_manager#1084]
Hey everyone!

I'm currently getting the following error while trying to integrate the [Google Maps SDK](https://github.com/googlemaps/ios-maps-sdk):
```
Error in fail: Unexpected link type for target. target: GoogleMaps, link_type: unknown, expected: static, dynamic
```

It seems to be because the result of `file --brief` on the 2 `.a` in `GoogleMaps.xcframework` results in the outputs:
```
ios-arm64/GoogleMaps.a: Mach-O 64-bit object arm64
```
```
Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit object x86_64] [arm64]
ios-arm64_x86_64-simulator/GoogleMaps.a (for architecture x86_64):	Mach-O 64-bit object x86_64
ios-arm64_x86_64-simulator/GoogleMaps.a (for architecture arm64):	Mach-O 64-bit object arm64
```

The [code handling the result](https://github.com/cgrindel/rules_swift_package_manager/blob/main/swiftpkg/internal/artifact_infos.bzl#L129-L140) is expecting either `ar archive` or `dynamic`, which is not the case and so defaults to `unknown`.

I'm not sure what the fix could be - [this post](https://forums.developer.apple.com/forums/thread/736719) suggests using `otool -l` and checking for a `LC_ID_DYLIB` for a dynamic library, maybe that can be used as a more robust check for dynamic libraries, and then maybe if a library doesn't have this it could be considered `static`?

I'd be glad to make that change if that's an acceptable solution

**Comment by cgrindel** [comment]
I think your suggestion sounds good. Are you thinking that we would update `repository_files.file_type()` to run `otool -l` if we do not find an output from `ar` that we recognize?

**Comment by stephanecopin** [comment]
Maybe not in `file_type` as it doesn't check for anything itself (it just returns the result of `file --brief`). I was thinking of adding a new method `artifact_infos.library_load_commands` potentially? And then in `artifact_infos.link_type` call `repository_files.file_type` first, and if unknown call `artifact_infos.library_load_commands`. How does that sound?

**Comment by cgrindel** [comment]
OK. SGTM.
