### ISSUE TITLE
Propagates preprocessor SWIFT_PACKAGE 

### ISSUE THREAD

**Issue by leohidalgo** [cgrindel/rules_swift_package_manager#1093]
I have a target that when it depends on an SPM package, the preprocessor definition `SWIFT_PACKAGE` becomes true.

I think that the expected behavior should have a value of false.

**Comment by brentleyjones** [comment]
True, it should only be set for the target itself, instead of propagated. Basically `local_define` instead of `define`.

**Comment by cgrindel** [comment]
@leohidalgo Can you check if #1094 fixes your issue?

**Comment by leohidalgo** [comment]
> @leohidalgo Can you check if #1094 fixes your issue?

It works, thanks.

**Comment by keith** [comment]
I'm not really sure this is the right fix as an objc target can use SWIFT_PACKAGE in its hdrs and expect it to be set when it is consumed. I think I can workaround this in the current case where folks found this though.

**Comment by cgrindel** [comment]
> I'm not really sure this is the right fix as an objc target can use SWIFT_PACKAGE in its hdrs and expect it to be set when it is consumed. I think I can workaround this in the current case where folks found this though.

@keith Do you think we need to revert this?
