### ISSUE TITLE
`flag provided but not defined: -repo_config` when migrating to bzlmod

### ISSUE THREAD

**Issue by jpsim** [cgrindel/rules_swift_package_manager#354]
I'm on 0.4.2 without bzlmod and it appears to be working well, but now trying to use bzlmod I'm getting this error:

```
$ bazel run //bazel:swift_update_pkgs
INFO: Invocation ID: eeddf74e-075f-4093-a3be-6dafce695a61
INFO: Analyzed target //bazel:swift_update_pkgs (1 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target //bazel:swift_update_pkgs up-to-date:
  bazel-bin/bazel/swift_update_pkgs-runner.bash
  bazel-bin/bazel/swift_update_pkgs
INFO: Elapsed time: 0.498s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Running command line: bazel-bin/bazel/swift_update_pkgs
INFO: Build completed successfully, 1 total action
flag provided but not defined: -repo_config
gazelle: Try -help for more information
```

I'll try to get a full reproducer later, but I want to post this for now in case you immediately had an idea of what this could be.

I'm on bazel 6.1.1 btw.

**Comment by cgrindel** [comment]
This is [a bug in Gazelle 0.30.0](https://github.com/bazelbuild/bazel-gazelle/pull/1501). I have asked for a patch release. It sounds like the maintainers are trying to coordinate a rules_go and gazelle release.

**Comment by cgrindel** [comment]
I am going to close this issue. Let me know if you would like me to reopen.

**Comment by jpsim** [comment]
Downgrading gazelle to 0.29.0 worked, thanks!
