### ISSUE TITLE
Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'

### ISSUE THREAD

**Issue by denis15yo** [cgrindel/rules_swift_package_manager#372]
When using ObjC dependency you will get "Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'" if there are Bundle Resources.

Package example https://github.com/AppLovin/AppLovin-MAX-Swift-Package

**Comment by cgrindel** [comment]
@denis15yo Sorry for the delay. I have not dug into this. I just did some searching. It looks like this may be an SPM issue. 

Related links
- https://github.com/apple/swift-package-manager/issues/4500

Curious. What version of Swift are you using?
