### ISSUE TITLE
Packages using the `Bundle.module` SwiftPM-generated bundle accessor fails to compile

### ISSUE THREAD

**Issue by jpsim** [cgrindel/rules_swift_package_manager#491]
SwiftPM generates a `Bundle.module` static Swift accessor to access the package's resource bundle.

If such a package is integrated with rules_swift_package_manager it fails to compile because rules_swift_package_manager/bazel doesn't codegen that same accessor.

For example pulling in the Stripe SDK:

```swift
.package(
  url: "https://github.com/stripe/stripe-ios",
  from: "23.11.0"
)
```

Results in a build failure:

```
external/rules_swift_package_manager~0.7.1~swift_deps~swiftpkg_stripe_ios/StripeCore/StripeCore/Source/Helpers/StripeCoreBundleLocator.swift:15:48: error: type 'Bundle' has no member 'module'
        static let spmResourcesBundle = Bundle.module
                                        ~~~~~~ ^~~~~~
```

Separate but related: I'm curious how folks generally migrate code that uses `Bundle.module` from SwiftPM to Bazel for code that they control (e.g. not external dependencies).

**Comment by cgrindel** [comment]
Interesting. We have a [Bundle.module implementation](https://github.com/cgrindel/rules_swift_package_manager/blob/280609c4777970f59b587b39ea68b24feb1ebde4/swiftpkg/internal/ResourceBundleAccessor.swift.tmpl#L4) in `rules_swift_package_manager`. I wonder why it does not work for stripe. 🤔

**Comment by cgrindel** [comment]
> I'm curious how folks generally migrate code that uses Bundle.module from SwiftPM to Bazel for code that they control (e.g. not external dependencies).

I am not entirely sure what other folks do. However, I have come across several implementations of `Bundle.module` in other code bases. I suspect most folks just implement the function themselves.

**Comment by cgrindel** [comment]
@jpsim Do you know which target in `stripe-ios` that you were depending upon / building? 

I can try adding one or two of [the stripe-ios examples](https://github.com/stripe/stripe-ios/tree/master/Example) to the `examples` directory in `rules_swift_package_manager`. Which one(s) would be most useful in your opinion?

**Comment by cgrindel** [comment]
Quick update. I believe that I have a fix for this issue. (Not sure why, but the resources are listed in the description JSON and not the dump JSON for the Swift package. This was preventing the resource bundle from being defined and the `Bundle.module` from being generated.) Right now, I am adding [this example](https://github.com/stripe/stripe-ios/tree/master/Example/PaymentSheet%20Example) to the `examples` directory.

@jpsim I am about to leave on a short trip. If you need the fix urgently, let me know and I will create a PR with just the fix. Otherwise, I will push the fix, the example and an integration test in a single PR.

**Comment by jpsim** [comment]
I don’t need this urgently fixed, but I’m glad to see that you believe to have found a solution.

**Comment by erneestoc** [comment]
would be nice to dispatch the release workflow for this 🤔

**Comment by cgrindel** [comment]
@erneestoc Done. Release 0.8.0 will be available via bzlmod shortly. Watch [this PR](https://github.com/bazelbuild/bazel-central-registry/pull/872) for updates.

**Comment by erneestoc** [comment]
Thanks!

**Comment by erneestoc** [comment]
![Screenshot 2023-08-30 at 2 01 48 PM](https://github.com/cgrindel/rules_swift_package_manager/assets/1932403/eaec3edf-a7c1-4308-937a-d8f73c64b66d)

may need to re-open

**Comment by cgrindel** [comment]
@erneestoc Do you have a repro for the error that you are seeing?

**Comment by erneestoc** [comment]
Sample project https://github.com/erneestoc/bazel-spm-rules-bug
Run `bazel run //:swift_update_pkgs`
Then `bazel build //:SPMExample`

It will output:
```
external/rules_swift_package_manager~0.8.0~swift_deps~swiftpkg_messagekit/Sources/Extensions/Bundle+Extensions.swift:29:55: error: type 'Bundle' has no member 'module'
    static var messageKitAssetBundle: Bundle = Bundle.module
```

**Comment by cgrindel** [comment]
It looks like SPM does [find some resources](https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageDescription.md#resource) (e.g., XIB files, storyboards, Core Data file types, and asset catalogs) automatically. Unfortunately, these found resources do not appear in the dump or description JSON that is currently used to identify resources. It looks like we need to add discovery for these special resource types to `rules_swift_package_manager`.

**Comment by cgrindel** [comment]
Based upon [this code](https://github.com/apple/swift-package-manager/blob/main/Sources/PackageLoading/TargetSourcesBuilder.swift#L634-L677), it looks like we need to find the following resources:
- xib: "nib", "xib", "storyboard"
- assetCatalog: "xcassets"
- stringCatalog: "xcstrings"
- coredata: "xcdatamodeld", "xcdatamodel", "xcmappingmodel"
- metal: "metal"
