### ISSUE TITLE
Package with Two Products, with an Intradependency from One Product

### ISSUE THREAD

**Issue by ekohlwey** [cgrindel/rules_swift_package_manager#504]
Hi there,
I'm trying to use the swift Porter Stemmer library from https://github.com/scaraux/Swift-Porter-Stemmer-2.

During the build for `@swiftpkg_swift_porter_stemmer_2//:PorterStemmer2_Classes_Swift_PorterStemmer2`, there is a compiler error:

```
ERROR: /private/var/tmp/_bazel_ekohlwey/80429706e7731d7db50de017c57ccb50/external/swiftpkg_swift_porter_stemmer_2/BUILD.bazel:136:14: Compiling Swift module @swiftpkg_swift_porter_stemmer_2//:PorterStemmer2_Classes_Swift_PorterStemmer2 failed: (Exit 1): worker failed: error executing command (from target @swiftpkg_swift_porter_stemmer_2//:PorterStemmer2_Classes_Swift_PorterStemmer2) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc ... (remaining 1 argument skipped)
error: emit-module command failed with exit code 1 (use -v to see invocation)
external/swiftpkg_swift_porter_stemmer_2/PorterStemmer2/Classes/Swift/PorterStemmer.swift:17:8: error: no such module 'libstemmer'
import libstemmer
       ^
external/swiftpkg_swift_porter_stemmer_2/PorterStemmer2/Classes/Swift/PorterStemmer.swift:17:8: error: no such module 'libstemmer'
import libstemmer
       ^
```

I take it that this is because Bazel is unaware of the dependency between the `PorterStemmer2` product and the `libstemmer` product.

**Comment by cgrindel** [comment]
Is there any chance that you can put up a repro? It will help me be able to debug this quicker.

**Comment by cgrindel** [comment]
[Update from repro](https://github.com/cgrindel/rules_swift_package_manager/pull/505#issuecomment-1659239418).

It turns out that the Package.swift for the 0.1.1 version of Swift-Porter-Stemmer-2 has a bug. The PortStemmer2 module should have a dependency on libstemmer. Luckily, someone has already submitted [a fix](https://github.com/scaraux/Swift-Porter-Stemmer-2/commit/5e90cdbc3700a1bf0b8083ba1117c8c4e48669a6). So, you just need to use the repo at that commit.

Let me know if this fixes the issue on your end.

**Comment by cgrindel** [comment]
@ekohlwey Have you had a chance to try the updated `Package.swift` for `Swift-Porter-Stemmer`?

**Comment by cgrindel** [comment]
I am going to close this issue as I believe that the resolution is described above. Feel free to reopen the issue if you. need additional help.

**Comment by ekohlwey** [comment]
Hi thank you, I have not yet tried the porter stemmer package but I am working on an example for this repo that has a similar configuration scenario, and it appears to be working as expected.
