### ISSUE TITLE
feat: Add configuration to gazelle plugin to selectively generate swift grpc library flavors.

### ISSUE THREAD

**Issue by AttilaTheFun** [cgrindel/rules_swift_package_manager#509]
Initially I just made the gazelle plugin generate all of the flavors (client, client_stubs, and server). This shouldn't cause any issues since, if nothing depends on them, they'll never be evaluated. To produce "cleaner" BUILD files, though, it would be nice to have a gazelle configuration to only generate a subset of these. E.g. if the protos are only being used on the client, there is no need to generate the server protos.

**Comment by cgrindel** [comment]
Per [a recent Slack thread](https://bazelbuild.slack.com/archives/CD3QY5C2X/p1696950765107109?thread_ts=1696946243.388449&cid=CD3QY5C2X), we need to provide a way for a client to disable the generation of all Swift GRPC targets.
