### ISSUE TITLE
Support for shake_ios

### ISSUE THREAD

**Issue by joune** [cgrindel/rules_swift_package_manager#615]
shake_ios is distributed as an xcframework, but unlike Lottie, not packaged as a zip file. 
See https://github.com/cgrindel/rules_swift_package_manager/pull/614 for a patch to workaround the issue. Please advise on a proper way to handle this. 🙏

**Comment by cgrindel** [comment]
Thanks for submitting the issue. 

Ideally, the package manifest information (e.g., dump JSON, description JSON) provides information that we can use to detect and handle this type of `binaryTarget`.

**Comment by joune** [comment]
The binary target is correctly detected but the problem comes with the packaging of the framework: the rule implementation only expects to download a zip file, which is not the case for shake.
