### ISSUE TITLE
`generate_swift_deps_for_workspace = False` still requires a `swift_deps.bzl` file

### ISSUE THREAD

**Issue by luispadron** [cgrindel/rules_swift_package_manager#686]
Given this setup:

```bzl
# Ignore the Swift build folder
# gazelle:exclude .build
swift_update_packages(
    name = "update_packages",
    gazelle = ":rules_swift_package_manager_gazelle",
    generate_swift_deps_for_workspace = False,
    package_manifest = "ThirdParty/SPM/Package.swift",
    swift_deps_index = "ThirdParty/SPM/swift_packages_index.json",
    update_bzlmod_stanzas = True,
    update_bzlmod_use_repo_names = True,
)
```

When I run the update packages command in Bzlmod without a `ThirdParty/SPM/swift_packages.bzl`, I get this error:

```sh
gazelle: loading WORKSPACE file: failed to load /Users/lpadron/Development/cash-ios/ThirdParty/SPM/swift_packages.bzl in repoRoot /Users/lpadron/Development/cash-ios: open /Users/lpadron/Development/cash-ios/ThirdParty/SPM/swift_packages.bzl: no such file or directory
```

If I add an empty file the update works and the file remains empty.

Should the expected behavior be that this file is no longer required and thus can be deleted? If so, we should fix this such that we dont try to write to this file if `generate_swift_deps_for_workspace == False`

**Comment by cgrindel** [comment]
You want to set [generate_swift_deps_for_workspace](https://github.com/cgrindel/rules_swift_package_manager/blob/main/docs/rules_and_macros_overview.md#swift_update_packages-generate_swift_deps_for_workspace) to `False`. Here is [an example](https://github.com/cgrindel/rules_swift_package_manager/blob/main/examples/firebase_example/BUILD.bazel#L34).

**Comment by cgrindel** [comment]
Sorry. I missed that you had that attribute specified. 👀

**Comment by luispadron** [comment]
I can take a look at this
