### ISSUE TITLE
feat: Add support for Swift packages which require .netrc authentication to download prebuilt frameworks

### ISSUE THREAD

**Issue by AttilaTheFun** [cgrindel/rules_swift_package_manager#688]
I'm encountering a different error when trying to use MapBox as an SPM dependency through rules_swift_package_manager.
```
ERROR: /private/var/tmp/_bazel_logan/1778e05be3eb20c760d71dcb3041f467/external/rules_swift_package_manager~override~swift_deps~swiftpkg_mapbox_maps_ios/BUILD.bazel:88:14: @rules_swift_package_manager~override~swift_deps~swiftpkg_mapbox_maps_ios//:Sources_MapboxMaps depends on @rules_swift_package_manager~override~swift_deps~swiftpkg_mapbox_core_maps_ios//:Sources_MapboxCoreMapsWrapper in repository @rules_swift_package_manager~override~swift_deps~swiftpkg_mapbox_core_maps_ios which failed to fetch. no such package '@rules_swift_package_manager~override~swift_deps~swiftpkg_mapbox_core_maps_ios//': java.io.IOException: Error downloading [https://api.mapbox.com/downloads/v2/mobile-maps-core/releases/ios/packages/10.16.1/MapboxCoreMaps.xcframework-dynamic.zip] to /private/var/tmp/_bazel_logan/1778e05be3eb20c760d71dcb3041f467/external/rules_swift_package_manager~override~swift_deps~swiftpkg_mapbox_core_maps_ios/remote/archive/MapboxCoreMaps.xcframework-dynamic.zip/temp7739357637349871279/MapboxCoreMaps.xcframework-dynamic.zip: GET returned 401 Unauthorized
```

Their setup is unusual in that you need an access token in your HOME/.netrc file to download the SDK from the URLs in their Package.swift file:
https://github.com/mapbox/mapbox-maps-ios/blob/main/Package.swift

I got it working through Xcode but it's not working through rules_swift_package_manager.

There is a bazelbuild/bazel thread about netrc authentication here:
https://github.com/bazelbuild/bazel/issues/13709

I think we could modify your repo_rules.bzl file as they describe here to support it:
https://github.com/bazelbuild/bazel/issues/13709#issuecomment-1336699672

**Comment by luispadron** [comment]
I think folks who require this kind of auth would be better off using [Bazel's new credentials helper](https://groups.google.com/g/bazel-discuss/c/mwLotKlERh4) which is designed for that purpose vs. building something custom in this repository.

**Comment by luispadron** [comment]
Actually if it's just for netrc I can see use in extending the rules here to support this with the core netrc stuff Bazel has.

**Comment by luispadron** [comment]
Here's similar implementation in rules_scala: https://github.com/bazelbuild/rules_scala/commit/0391ef4e43fecac5b63518082294e2151f74aeb4

**Comment by cgrindel** [comment]
If the credential helper support solves this issue, I think that we should not add something specific to `rules_swift_package_manager`. Here is [the implementation PR](https://github.com/bazelbuild/bazel/pull/18173). Does this work for your situation @AttilaTheFun ?

**Comment by luispadron** [comment]
I haven't found too many docs on that flag fwiw, so if ya'll have more that would be sweet. We should at least investigate if it's standard for rules to add the `netrc` auth support into their repo rules directly. I had forgotten bazel provides utils for auth with netrc specifically and if that helps not require any extra stuff for our users it might be nice to add.

If creds helper supports netrc easily though, we could just recommend that.

**Comment by AttilaTheFun** [comment]
Following up here, I've got the credential helper working now.

There were actually three issues at play:
- Firstly, the Bazel implementation (HttpConnectorMultiplexer) is not following the specification which states that the Bazel build should fail with an error if the credential helper exits with a nonzero status code or produces malformed output. It's currently swallowing the error and attempting to connect anyways which fails with a 401 HTTP error. We can keep the issue open for this.
- Secondly, I was missing a shebang at the top of my python script. I needed to add #!/usr/bin/env python3  so it could run as an executable. It was unclear that this was failing because the above issue was swallowing the error.
- And thirdly, I misread the spec and expected the command, "get", to be passed via standard input rather than as a positional CLI argument. Once I read the command from sys.argv instead of stdin, it worked.

I pushed my changes to fix the script and replied on the issue in the event this helps anyone else.

@cgrindel @luispadron  once I fixed this issue, I was able to fetch the Mapbox swift package dependency as expected.
I'll close out the feature request.

If anyone else encounters this issue, you can check out my example repository here:
https://github.com/AttilaTheFun/credential_helper_example
