### ISSUE TITLE
feat: Add support for packages with Swift macros

### ISSUE THREAD

**Issue by jpsim** [cgrindel/rules_swift_package_manager#700]
Swift macros were introduced in Swift 5.9: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/macros/

rules_swift added support for Swift macros in 1.11.0: https://github.com/bazelbuild/rules_swift/blob/master/doc/rules.md#swift_compiler_plugin

Swift packages with macros are gaining popularity and adoption, with a collection of macro packages available here, which could be good candidates for examples and integration tests: https://github.com/krzysztofzablocki/Swift-Macros

**Comment by cgrindel** [comment]
@jpsim Can you add a link to the Swift package where you ran into Swift macros in the wild?

**Comment by cgrindel** [comment]
>I’d rather not focus on that project necessarily since it was just a development branch and macro integration hasn’t been merged yet.

If we don't have an example of a published Swift package using macros, we will need to create a Swift package that does use them and add it to an example.

**Comment by cgrindel** [comment]
Sorry. I missed the last link. 😳
