### ISSUE TITLE
unable to resolve modules

### ISSUE THREAD

**Issue by joprice** [cgrindel/rules_swift_package_manager#732]
When I try running  `bazel run //:swift_update_pkgs`, I get an error mentioning the redefinition of many modules. I also notice that even though I have platforms set to ios, I see the macos sdk being used. I assume I have something misconfigured, but not sure where to start debugging.

```
Updating https://github.com/ciaranrobrien/SwiftUIFlow
Updated https://github.com/ciaranrobrien/SwiftUIFlow (0.56s)
error: Invalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/vr/1nkn3qgj28j9lzk0b5px0gm00000gn/T/TemporaryDirectory.NgUaNj/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "x86_64-apple-macosx13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-package-description-version", "5.5.0", "/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/vr/1nkn3qgj28j9lzk0b5px0gm00000gn/T/TemporaryDirectory.iFJ85t/swiftuiflow-manifest"])
error: fatalError
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/module.modulemap:1:8: error: redefinition of module 'AppleTextureEncoder'
module AppleTextureEncoder [system] {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/module.modulemap:1:8: note: previously defined here
module AppleTextureEncoder [system] {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/module.modulemap:6:8: error: redefinition of module 'Compression'
module Compression [system] {```

**Comment by cgrindel** [comment]
Could you provide the `Package.swift` dependency declaration?

**Comment by joprice** [comment]
Here is the relevant part of the Package.swift file:

 ``` dependencies: [
      .package(
        url: "https://github.com/ciaranrobrien/SwiftUIFlow.git",
        revision: "b300d3c0110116f3520066dfb8dcf3006cf593c3")
    ]
```

I think it has something to do with my environment or bazel config though, since I get similar errors for anything I attempt to install.

**Comment by cgrindel** [comment]
In #770, I added `SwiftUIFlow` to our `resources_example`. It appears to build properly. Have you had any luck chasing down the configuration issues that mentioned?

**Comment by joprice** [comment]
I haven't. I've ended up building everything manually using http_archive and swift_library. It's probably something I still don't understand about platform flags in my bazelrc. I'll close since it's obviously not a problem with these rules and when I get some free time, try to build an example from the repo and see if I can figure it out.

**Comment by joprice** [comment]
I was finally able to get around this by first removing my simulator folder from `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/Developer/Platforms/iPhoneSimulator.platform`, which revealed a new error where multiple modulemaps were found, one from the xcode toolchain and one from `/usr/local/include/swift`. I unlinked the latter and restored the simulator platform, and I was able to get `swift package update` and the rules generation to run.
