### ISSUE TITLE
Feature request: Better support for built-in framework determination

### ISSUE THREAD

**Issue by luispadron** [cgrindel/rules_swift_package_manager#742]
There are two sub issues I'd like made better:

## Overview

- [x] We are unable to correctly determine when something is a built-in framework.
  - https://github.com/cgrindel/rules_swift_package_manager/pull/749
  - https://github.com/cgrindel/rules_swift_package_manager/pull/750

- [x] We are unable to differentiate between a local framework and a built-in framework of the same name.
  - https://github.com/cgrindel/rules_swift_package_manager/pull/756

## Details 

1. I have several frameworks which import things like `Darwin`, since `Darwin` is not included as a [built-in framework here](https://github.com/cgrindel/rules_swift_package_manager/blob/main/gazelle/internal/swift/builtin_modules.go). This causes a bug similar to the one seen in #728 where the plugin would add a random dep to the target. We need to generate this list so that it's at least more complete.

2. I have a framework named `System`, since `System` is defined as a built-in framework the gazelle generation does not work as expected. It fails to add `System` as a dep of things that use it as it believes its a built-in framework. We need better support for differentiating between frameworks and built-in frameworks with the same name.

**Comment by cgrindel** [comment]
Do you have thoughts on how to mitigate these issues?

1. We can/should add `Darwin` to the [list of special built-ins](https://github.com/cgrindel/rules_swift_package_manager/blob/6023ab6055d225c64cff50f73da87dd78d3491d3/gazelle/internal/swift/is_builtin_module.go#L5-L8).
2. We could add a directive that allows a client to provide their own mapping for select modules.

**Comment by luispadron** [comment]
Yeah so my current thoughts are:

For 1, we could look at updating the list to include swift modules like I had in my PR before undoing that change. It had some other issues but general think it ended up picking a larger set of actual built-in frameworks (im not sure on why the frameworks directory doesnt include these).

For 2, I was hoping this wouldn't have to be configured by users, using `System` as a module name for example should just work. I think this relates a lot to the [discussion you opened already](https://github.com/cgrindel/rules_swift_package_manager/discussions/743). I imagine it's going to be tough to figure this out without directly parsing `Package.swift`

**Comment by cgrindel** [comment]
On second thought, perhaps we could solve issue 2 by introducing a priority. Any modules discovered in a client's workspace should take precedence over any of the others. We could tier it even further, if necessary. 🤔

**Comment by luispadron** [comment]
> On second thought, perhaps we could solve issue 2 by introducing a priority. Any modules discovered in a client's workspace should take precedence over any of the others. We could tier it even further, if necessary. 🤔

That works! Do you have quick reference to where that logic might be added
