### ISSUE TITLE
Bug: Gazelle requires `WORKSPACE` when updating packages in a bzlmod only repo

### ISSUE THREAD

**Issue by luispadron** [cgrindel/rules_swift_package_manager#744]
When running the `update_swift_packages` target in a repo with only `MODULE.bazel` and `WORKSPACE.bzlmod` we get the following error:

```
gazelle: loading WORKSPACE file: open /Users/<user>/Development/<repo>/WORKSPACE: no such file or directory
```

Target config:

```bzl
swift_update_packages(
    name = "update_packages",
    gazelle = ":rules_swift_package_manager_gazelle",
    generate_swift_deps_for_workspace = False,
    package_manifest = "ThirdParty/SPM/Package.swift",
    swift_deps_index = "ThirdParty/SPM/swift_packages_index.json",
    update_bzlmod_stanzas = True,
    update_bzlmod_use_repo_names = True,
)
```

**Comment by cgrindel** [comment]
What version of Gazelle are you using? I submitted [a fix to Gazelle](https://github.com/bazelbuild/bazel-gazelle/pull/1589) in August.

**Comment by luispadron** [comment]
Was using [0.33.0](https://registry.bazel.build/modules/gazelle/0.33.0) for this

**Comment by luispadron** [comment]
I believe the error is coming from here: https://github.com/bazelbuild/bazel-gazelle/blob/0205c200e7bc61270e7b1b2f081df929289e6aa1/cmd/gazelle/update-repos.go#L109-L118

**Comment by luispadron** [comment]
I'm going to close this here, it seems like the issue is with gazelle itself.
