### ISSUE TITLE
Unbuildable generated `swift_test` target when testing `executableTarget`

### ISSUE THREAD

**Issue by luispadron** [cgrindel/rules_swift_package_manager#752]
Given an `executableTarget` and a `testTarget` which depends on the `executableTarget`. In this scenario gazelle plugin will generate a `swift_binary` and a `swift_test` accordingly. The `swift_test` will depend on `swift_binary` which leads to a module not found build error:

```
Tests/MyExecutableTests/MyExecutableTests.swift:1:18: error: no such module 'MyExecutable'
@testable import MyExecutable
                 ^
```

See the PR showcasing this issue in #751

**Comment by luispadron** [comment]
This almost feels like a usability issue of `rules_swift`, why isn't the `swift_test` correctly picking up the library that binary is using.

@cgrindel is this something you've looked at before? I can find out more info on the rules_swift side if you think we should go that route. 

Or we can generate a `swift_library` for every `swift_binary`. We'd have to come up with a naming pattern here though.

**Comment by cgrindel** [comment]
Typically, one does not depend upon an executable. If you need the binary in a test, you want to pass it via `data`. If you are trying to write unit tests for functionality that is in a binary, then I would separate the code so that the items to be unit tested are in a `swift_library`.

**Comment by luispadron** [comment]
Makes sense, this works with SPM though and is a common pattern from some of the projects I've seen. 

Right now the only way to support this is to disable generation in the build file for the executable target and make a swift_library that is used by the binary and the unit test. 

Should we update generation to create a library for each executable target?

**Comment by luispadron** [comment]
@cgrindel yeah exactly, it runs unit tests on the library of the binary. A binary target may include unit testable code for example.

Here is what the SPM file would look like:

```swift
// swift-tools-version: 5.7

import PackageDescription

let package = Package(
    name: "MySwiftPackage",
    products: [
        .executable(name: "my-executable", targets: ["MyExecutable"]),
    ],
    dependencies: [ ... ],
    targets: [
        .executableTarget(
            name: "MyExecutable",
            dependencies: [ ... ],
            path: "Sources/MyExecutable",
            exclude: ["BUILD.bazel"]
        ),
        .testTarget(
            name: "MyExecutableTests",
            dependencies: ["MyExecutable"],
            path: "Tests/MyExecutableTests",
            exclude: ["BUILD.bazel"]
        ),
    ]
)

```

In SPM with the above `swift test` works as expected.

**Comment by cgrindel** [comment]
Something just occurred to me. Is this an issue with the repository rules or the Gazelle plugin? IIRC, `rules_swift_package_manager` does not generate test targets in the repository rules and the Gazelle plugin does not look at package manifests.

**Comment by luispadron** [comment]
Hmm I thought this would be coming from the Gazelle code gen since its the thing I assumed generated the BUILD files? I have an example of this issue up here: https://github.com/cgrindel/rules_swift_package_manager/pull/751

**Comment by luispadron** [comment]
I'm going to close this, I believe this is better fixed upstream in `rules_swift`. A `swift_binary`'s library should be importable the same way `swift_library` is.

I looked at generating a `swift_library` and `swift_binary` here but this breaks whenever the binary name and the library name are the same (which is valid in SPM) as Bazel doesn't allow targets of the same name in the same package.

**Comment by cgrindel** [comment]
> Is this an issue with the repository rules or the Gazelle plugin? 

I wonder if this issue appeared after adding a Bazel package to a child workspace and not running the [`update_deleted_packages` utility](https://github.com/cgrindel/rules_swift_package_manager/blob/main/BUILD.bazel#L34)? The Gazelle plugin in the parent workspace would see the package and attempt to generate test targets. 🤔

**Comment by luispadron** [comment]
I don't think this is an issue with this repo actually. I just put a PR that should resolve this in rules_swift.
