### ISSUE TITLE
Do not add `.build` directory when running `:swift_update_pkgs`

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/rules_swift_package_manager#758]
In #747, we added a `.bazelignore` to the `tca_example`. None of the other examples require this. We should understand why this is happening.

Related: Some clients have requested that the `.build` directory not be placed in the workspace. There are several options:

1. Remove the `.build` directory after running `swift_update_pkgs`. The downside is that some clients may want a `.build` directory for the Swift LSP to work properly.
2. Specify `--build-path` when running Swift package resolution and place it elsewhere. Maybe in a temp directory?

**Comment by jpsim** [comment]
tca_example needs this because it pulls in a Swift Package that has Bazel build files (swift-syntax), and that's discovered when doing `bazel (build|test) //...` because the `//...` catches it.
