### ISSUE TITLE
The `RxTest` module for `ReactiveX/RxSwift` does not compile.

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/rules_swift_package_manager#791]
### Background

`rules_swift_package_manager` inspects the code of the Swift packages looking for certain imports and directives. These influence some of the build attributes for their respective targets. For instance, if a source file imports `XCTest`, we need to set the `testonly = True` attribute on the library that includes the source file. (`rules_swift` performs some magic to ensure that `XCTest` and some other libraries are available when the attribute is enabled.)

As of the writing of this issue, `rules_swift_package_manager` [ignores imports](https://github.com/cgrindel/rules_swift_package_manager/blob/3bcdf6d4fe4d1d294d4fbddd761538b1965450d0/swiftpkg/tests/swift_files_tests.bzl#L146-L158C11) that occur conditional compilation blocks (i.e., `#if ... #endif`). 

Unfortunately, this logic prevents the following pattern as seen in `RxTest` from being found:

```swift
#if !os(watchOS)
import RxSwift
import XCTest
// ...
#endif
```

### Error

```
ERROR: /private/var/tmp/_bazel_chuck/b3a10cdb733676f9336ceead7023800c/rules_xcodeproj.noindex/build_output_base/external/rules_swift_package_manager~override~swift_deps~swiftpkg_rxswift/BUILD.bazel:452:14: Compiling Swift module @rules_swift_package_manager~override~swift_deps~swiftpkg_rxswift//:Sources_RxTest failed: (Exit 1): worker failed: error executing command (from target @rules_swift_package_manager~override~swift_deps~swiftpkg_rxswift//:Sources_RxTest)
  (cd /private/var/tmp/_bazel_chuck/b3a10cdb733676f9336ceead7023800c/rules_xcodeproj.noindex/build_output_base/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=17.0 \
    SWIFT_AVOID_WARNING_USING_OLD_DRIVER=1 \
    XCODE_VERSION_OVERRIDE=15.0.1.15A507 \
  bazel-out/darwin-opt-exec-2B5CBBC6-ST-477482371507/bin/external/rules_swift~1.13.0/tools/worker/worker swiftc @bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-dd040315e354/bin/external/rules_swift_package_manager~override~swift_deps~swiftpkg_rxswift/RxTest.swiftmodule-0.params)
# Configuration: 9f4a5e0e22ca5e241f1ef40d1b97868683614cd048311aaf26967c56a83c859c
# Execution platform: @local_config_platform//:host
error: emit-module command failed with exit code 1 (use -v to see invocation)
external/rules_swift_package_manager~override~swift_deps~swiftpkg_rxswift/Sources/RxTest/XCTest+Rx.swift:11:8: error: no such module 'XCTest'
import XCTest
       ^
external/rules_swift_package_manager~override~swift_deps~swiftpkg_rxswift/Sources/RxTest/XCTest+Rx.swift:11:8: error: no such module 'XCTest'
import XCTest
       ^
error: fatalError
INFO: Elapsed time: 56.873s, Critical Path: 19.48s
INFO: 227 processes: 18 disk cache hit, 117 internal, 85 local, 7 worker.
FAILED: Build did NOT complete successfully
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/b6f9ab08-e33b-48df-b884-8483bf6d2987
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

error: The bazel build failed, please check the report navigator, which may have more context about the failure.

note: Run script build phase 'Copy Bazel Outputs / Generate Bazel Dependencies (Index Build)' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'FooTests' from project 'App')
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Generate\ Bazel\ Dependencies /Users/chuck/Library/Developer/Xcode/DerivedData/App-ekijcqnnerdhznafrcwpmcfafznd/Build/Intermediates.noindex/App.build/rules_xcodeproj/Script-B38FFB6BCB4532CDE9B28C2F.sh (in target 'BazelDependencies' from project 'App')
(1 failure)
```

### Options

1. We could add a directive that allows a client to specify whether imports in conditionals should be found. I don’t love this, but it would be fairly straightforward to implement.
2. We could inspect the `#if` and only ignore it if it is a define variable (e.g. `DEBUG`). This feels a bit better.
3. Same as option 2, but only ignore imports in conditionals if they are guarded by the `DEBUG` define value. All of the other conditionals that have imports would be found.

I am leaning toward implementing option 3.

### Repro Info

Package dependency:

```swift
        .package(url: "https://github.com/ReactiveX/RxSwift.git", exact: "6.6.0"),
```

**Comment by jpsim** [comment]
I'm also running into incorrect test-only discovery for the `InlineSnapshotTesting` target from https://github.com/pointfreeco/swift-snapshot-testing.

How would you feel about hardcoding some know test-only modules as a stopgap until the test-only discovery is improved?

```
# The rules_swift code links in developer libraries if the rule is marked testonly.
# https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/compiling.bzl#L1312-L1319
if target.swift_src_info.imports_xctest:
    attrs["testonly"] = True
# Until test-only discovery is improved, explicitly add some known test-only targets.
elif target.c99name == "InlineSnapshotTesting" or target.c99name == "RxTest":
    attrs["testonly"] = True
```

**Comment by cgrindel** [comment]
> How would you feel about hardcoding some know test-only modules as a stopgap until the test-only discovery is improved?

A little queasy.

A feature that I have noodled about for a while is providing a means for the client to modify the generated declarations. I imagined that the client would specify these modifications using a bzlmod extension. Perhaps I should start a discussion to see what folks think. 🤔

**Comment by cgrindel** [comment]
I created #852 to facilitate a discussion on how to help unblock clients when they encounter edge cases that `rules_swift_package_manager` does not support.

**Comment by cgrindel** [comment]
I started [a Slack thread](https://bazelbuild.slack.com/archives/CD3QY5C2X/p1705863416638509) suggesting a change to `rules_swift` that should allow us to better support Swift packages with conditional `XCTest` imports.

**Comment by cgrindel** [comment]
Once a new release of `rules_swift` is published that includes https://github.com/bazelbuild/rules_swift/pull/1162, I have a PR ready for `rules_swift_package_manager` that uses the new attribute.
