### ISSUE TITLE
duplicate symbol '_OBJC_CLASS_$___CurrentBundleFinder'

### ISSUE THREAD

**Issue by denis15yo** [cgrindel/rules_swift_package_manager#798]
I get an error when I try to add two packages at the same time: [Applovin](https://github.com/AppLovin/AppLovin-MAX-Swift-Package) and [SDWebImage](https://github.com/SDWebImage/SDWebImage)
Error message

> duplicate symbol '_OBJC_CLASS_$___CurrentBundleFinder' in:
    bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-dbg-ST-bfbdc696ffa7/bin/external/swiftpkg_applovin_max_swift_package/libSources_AppLovinSDKResources.a(Sources_AppLovinSDKResources_objc_resource_bundle_accessor_impl_ObjcResourceBundleAccessor.o)
    bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-dbg-ST-bfbdc696ffa7/bin/external/swiftpkg_sdwebimage/libSDWebImage_SDWebImage.a(SDWebImage_SDWebImage_objc_resource_bundle_accessor_impl_ObjcResourceBundleAccessor.o)
duplicate symbol '_OBJC_METACLASS_$___CurrentBundleFinder' in:
    bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-dbg-ST-bfbdc696ffa7/bin/external/swiftpkg_applovin_max_swift_package/libSources_AppLovinSDKResources.a(Sources_AppLovinSDKResources_objc_resource_bundle_accessor_impl_ObjcResourceBundleAccessor.o)
    bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-dbg-ST-bfbdc696ffa7/bin/external/swiftpkg_sdwebimage/libSDWebImage_SDWebImage.a(SDWebImage_SDWebImage_objc_resource_bundle_accessor_impl_ObjcResourceBundleAccessor.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cgrindel** [comment]
I forgot to incorporate the module name into the [`__CurrentBundleFinder` name](https://github.com/cgrindel/rules_swift_package_manager/blob/f31f5b6cd4e8c52f7be2d8b1972a203140983b6c/swiftpkg/internal/ObjcResourceBundleAccessor.m.tmpl#L6C17-L6C38). 

I should be able to get a fix out, this week.
