### ISSUE TITLE
advice: suppressing build warnings

### ISSUE THREAD

**Issue by joprice** [cgrindel/rules_swift_package_manager#801]
I'm building a swift target that has `-warnings-as-errors` enabled, which depends on Crashlytics. The build fails due to a macro redefinition warning. I'd like to have warnings-as-errors apply to my own source, but not to libraries. Ideally, I could silence it only for the Crashlytics target, but I can't seem to find a customization point where I can add copts that would be passed to the command compiling Crashlytics. Is there a way to pass something like `-Wno-builtin-macro-redefined` via the swift compiler or a way to customize the generated rules with values for attributes likes `copts`? 

```
<built-in>:396:2: note: in file included from <built-in>:396:
# 1 "<comerror: fatalError
mand line>" 1
 ^
<command line>:27:9: error: 'CLS_SDK_NAME' macro redefined
#define CLS_SDK_NAME Crashlytics macOS SDK
        ^
<command line>:26:9: note: previous definition is here
#define CLS_SDK_NAME Crashlytics iOS SDK
```

**Comment by cgrindel** [comment]
Have you tried using [--host_per_file_copt](https://bazel.build/reference/command-line-reference#flag--host_per_file_copt) or [--per_file_copt](https://bazel.build/reference/command-line-reference#flag--per_file_copt). I have seen these be used to apply flags to specific parts of the build.

**Comment by joprice** [comment]
I haven't. I'll try that method. Thanks!

**Comment by joprice** [comment]
I just tied it out and it works for the initial build of the dependency, but when building a target that depends on it, I see the error with `built-in` or `command line` as its source. I checked out the generated BUILD file and I do see what looks like duplicate defines:

 ```
defines = [
...
   "@rules_swift_package_manager//config_settings/spm/platform:ios": [
              "CLS_SDK_NAME=Crashlytics\\ iOS\\ SDK",
              "CLS_SDK_NAME=Crashlytics\\ macOS\\ SDK",
          ],
```

**Comment by cgrindel** [comment]
That does not look right. Can you tell what our firebase example is missing? As part of the investigation into this issue, I would like to add something to our firebase example that will repro this failure.

**Comment by joprice** [comment]
I can try checking it out and see if I wind up with the same duplication, and then enable `-warnings-as-errors` to see if it fails similarly. But, perhaps it's something in my config that influences the platform selection? Or is this a pure package.swift -> bazel rules parsing transformation?

**Comment by cgrindel** [comment]
I am pretty sure [this is the cause](https://github.com/cgrindel/rules_swift_package_manager/blob/f7b7405cecf58b467bd9723ec6db9abfa5312a86/config_settings/spm/platform/platforms.bzl#L67-L70). I was not sure how to map `macCatalyst`.  I created #809 to test if changing this map affects any of the current tests/examples.

**Comment by cgrindel** [comment]
It is always nice to relearn things. As [the comment](https://github.com/cgrindel/rules_swift_package_manager/blob/f7b7405cecf58b467bd9723ec6db9abfa5312a86/config_settings/spm/platform/platforms.bzl#L67-L70) clearly states, `macCatalyst` is more like iOS then it is macOS.

I don't have any great ideas on how to address this. One thought is to detect the duplicate define and just pick one. Of course, we could pick the wrong one. 

@joprice @luispadron @jpsim Does anyone have any suggestions?

**Comment by joprice** [comment]
Is anyone making use of Catalyst via bazel? I was curious about it, but wound up on this issue https://github.com/bazelbuild/rules_apple/issues/658. If it's not a feasible use case at the moment, perhaps it could be ignored to fix the immediate issue and then re-introduced when rules_apple supports it.

**Comment by cgrindel** [comment]
> One thought is to detect the duplicate define and just pick one. Of course, we could pick the wrong one.

This is my best suggestion to avoid duplicate define values. I can try and take a look at this over the upcoming holiday.
