### ISSUE TITLE
feature request: Some kind of short aliases for imported packages to reference as deps

### ISSUE THREAD

**Issue by krypt-lx** [cgrindel/rules_swift_package_manager#805]
Generated names are generally relatively tidy, but then I got this monstrosity: 

```
"@swiftpkg_metrica_sdk_ios//:remote_archive_YandexMobileMetrica-4.5.2-ios-spm-4cf9781b-4e3e-4674-bbb3-5ab28cc9869a.zip_YandexMobileMetrica"
```
for this package:
```
.package(url: "https://github.com/yandexmobile/metrica-sdk-ios", from: "4.5.2"),
```

It would be nice to have relatively short and predictable names

**Comment by cgrindel** [comment]
This has come up previously. There are a few things that we could do to make some of the target names more predictable. To ensure that the target names do not collide, we use path information. I will try and write some ideas down and put out to the community for review.

**Comment by krypt-lx** [comment]
There is an issue with this particular example I didn't noticed initially:
generated name contains lib version, and the version is imported as "from", which means it can get automatically updated to 4.5.3, for example, breaking all deps for this package

**Comment by cgrindel** [comment]
The `from` in the `Package.swift` should not be a big deal. When you run `//:swift_update_pkgs`, we use SPM to resolve the Swift packages which, in turn, are added to the `swift_deps_index.json`. This file is used to download the Swift package code.

**Comment by cgrindel** [comment]
FYI. This should get better once #883 merges.

**Comment by cgrindel** [comment]
Now that #883 is merged and released. I am going to close this. Please let me know if you feel that this should be reopened.
