### ISSUE TITLE
bundle accessor fails to compile with xcodeproj previews 

### ISSUE THREAD

**Issue by joprice** [cgrindel/rules_swift_package_manager#820]
I'm using the xcodeproj rules, and when building for swiftui previews using `build_mode = "xcode",` I get the following error when building ZIPFoundation:

```
.../Library/Developer/Xcode/DerivedData/Litterat-ezbtuzjbufpfqkcdzqzukyvbwygn/Build/Intermediates.noindex/Previews/LibFramework/Intermediates.noindex/Litterat.build/bazel-out/ios-x86_64-min16.4-applebin_ios-ios_x86_64-dbg-ST-f5a0d3734755/bin/Lib/DerivedSources/GeneratedAssetSymbols.swift:16:48: error: 'module' is inaccessible due to 'internal' protection level
    private let resourceBundle = Foundation.Bundle.module
                                                   ^~~~~~
.../rules_xcodeproj.noindex/build_output_base/execroot/_main/bazel-out/ios-x86_64-min16.4-applebin_ios-ios_x86_64-dbg-ST-f5a0d3734755/bin/external/rules_swift_package_manager~override~swift_deps~swiftpkg_zipfoundation/Sources_ZIPFoundation_resource_bundle_accessor_ResourceBundleAccessor.swift:11:16: note: 'module' declared here
        static var module: Bundle = {
                        ^
```

I have a bunch that these files were not meant to be used by the xcode asset generation system, but not sure if I'm meant to exclude them somehow, or if the access level of the generated code should be changed to accommodate this workflow.

**Comment by joprice** [comment]
To add some context, I hit this when trying to use the xcode mode to get previews to work across an app that’s split across many swift_library’s. I ended up hitting other issues with that and switching back to bazel mode and getting it to work by wrapping the libraries in frameworks, so I think I have a path forward for now. I mostly use vim with sourcekit-lsp and compile-commands to dev so I’m not that interested in the xcode flow for now. But I’m still curious about this for cases where features like archive or others that only seem to work with the xcode build.

**Comment by luispadron** [comment]
@cgrindel we do not use Xcode mode with rules_xcodeproj. I'd also recommend others to not depend on that mode as it should be removed eventually

**Comment by cgrindel** [comment]
@joprice Thanks for the context. To date, we have not spent any time ensuring that the code generated by this ruleset works when compiled with Xcode. If you run into other issues, please let us know. We will try to help. For now, I am going to close this issue.
