### ISSUE TITLE
Generate tidier, shorter target Bazel labels for dependent Swift packages.

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/rules_swift_package_manager#859]
## Problem

Today, Bazel target labels for Swift packages that are imported by `rules_swift_package_manager` are generated using the SPM target's path. This makes for names that can be long, unwieldy, and in some cases unpredictable (e.g. `@swiftpkg_swift_nio//:Sources_NIO`, `@swiftpkg_bar//:weird_path_to_ModuleName`).  

Because we need to ensure that SPM product names and SPM target names do not collide, the Bazel target labels need to be unique. For instance, a Swift package may define a product called `Foo` and it might include two targets `Foo` and `Bar`.  The product `Foo` should not collide with the target `Foo`.

## Proposal

- Targets would be placed under a Bazel package called `Targets` (e.g. `//Targets:Foo`).
- Products would be placed under a Bazel package called `Products` (e.g. `//Products/Foo`). NOTE: We only map executable products to Bazel targets.

## Implementation Considerations

We do not want to break existing projects. So, for a time, we will need to support the current scheme. There are several options:

1. Create aliases for the products and targets in the new `Products` and `Targets` Bazel packages.
2. Introduce a flag that allows the client to select the target label mode.

[Related Slack thread](https://bazelbuild.slack.com/archives/C05NZSHE7FU/p1705522740340369?thread_ts=1705521196.253499&cid=C05NZSHE7FU)

**Comment by luispadron** [comment]
Proposal is nice, the target names currently can be long and this makes them more user friendly. 

In terms of how to control breakage, I'd probably prefer the flag until a certain release where we make it the default. It matches Bazel and aliases have issues with other rules like rules_xcodeproj

**Comment by brentleyjones** [comment]
Resolved with #883.
