### ISSUE TITLE
use with rules_swift's grpc rules

### ISSUE THREAD

**Issue by joprice** [cgrindel/rules_swift_package_manager#880]
I'm trying to use the grpc and protobuf rules provided by rules_swift, based on the example here: https://github.com/bazelbuild/rules_swift/tree/da4eafef6401442b8c1b481d43dfa65907e8bf23/examples/xplatform/grpc. When building, I get duplicate symbol errors like the following, since both rules_swift and Package.swift provide their own version of swift collections:

```
duplicate symbol '_$s11DequeModule0A0V8_StorageV8capacitySivpMV' in:
    bazel-out/ios_x86_64-fastbuild-ios-x86_64-min16.4-applebin_ios-ST-41c8c7b10629/bin/external/rules_swift~1.13.0~non_module_deps~com_github_apple_swift_collections/libDequeModule.a[13](Deque._Storage.swift.o)
    bazel-out/ios_x86_64-fastbuild-ios-x86_64-min16.4-applebin_ios-ST-41c8c7b10629/bin/external/rules_swift_package_manager~0.25.0~swift_deps~swiftpkg_swift_collections/libSources_DequeModule.a[13](Deque._Storage.swift.o)
```

For direct dependencies of the project, I can simply switch to the ruels_swift provided dependency, but for indirect dependencies I'm not sure what to do. Is there any workaround, either by having rules_swift_package_manager dependencies reuse this dependency, or providing the SPM version to rules_swift? I looked into the rules and it seems the label is defined as a private attribute: https://github.com/bazelbuild/rules_swift/blob/922d26e964ed04ac174a13f58a01b64124059ec0/swift/internal/swift_grpc_library.bzl#L420C35-L420C69, but perhaps there's some kind of aliasing that can be used to make it work. If not, would the suggestion be to vendor those rules and inline the SPM definition?

**Comment by joprice** [comment]
I was able to get this working by copying swift_grpc_library.bzl, swift_proto_library.bzl, and swift_protoc_gen_aspect.bzl into my project and modifying references to point to SPM dependencies, so it seems if this could be made configurable on the rules_swift side, it would allow managing all deps from SPM.

**Comment by cgrindel** [comment]
@AttilaTheFun put together [a PR](https://github.com/bazelbuild/rules_swift/pull/1140) that addresses this issue.

**Comment by AttilaTheFun** [comment]
Hi @joprice ! Yes my rules_swift PR rewrites swift_proto_library and swift_grpc_library into a new swift_proto_library rule which accepts fully configurable protoc / plugin binaries, and I have an associated PR into this repository to use it.

**Comment by joprice** [comment]
Oh wow I overlooked that one. That's great to see!

**Comment by joprice** [comment]
Closing since it's already represented as a pr and there's a copy paste workaround for now.
