### ISSUE TITLE
ibazel causes re-resolution on each build file change

### ISSUE THREAD

**Issue by joprice** [cgrindel/rules_swift_package_manager#886]
This may be a broader ecosystem question, as I'm not sure it's an issue with these rules: When I use ibazel to watch a single target such as an ios_application, on each build file change, there is a long process that kicks off querying for files to watch, along with a log "Recording actual commit" for each of my dependencies. The workaround is to exit ibazel when iterating on the build and run a single bazel command per change. 

Debugging this is a bit beyond my current bazel knowledge, but based on a log mentioning checking for cached targets that is printed on each build file change, I assume that ibazel is running a query that ends up accessing a target that kicks off a checking for the up to date value of a dependency. I can try to reproduce the query that ibazel runs and perhaps there is something in there that would be something that is missing the cache for some reason, or could be excluded from the ibazel query somehow.

**Comment by cgrindel** [comment]
I personally do not use `ibazel`. So, I have not run into this. With regard to ibazel behavior and possible optimizations, I would ask at https://github.com/bazelbuild/bazel-watcher.

With regard to `rules_swift_package_manager`, I presume that you are using the Gazelle plugin from this repository to update your Swift targets in your build files. Are the changes being made legitimate? Is the plugin only updating files when it is warranted?

**Comment by joprice** [comment]
I'm not yet using the plugin, as I had started out with a pre-existing build structure that I haven't cleaned up to work with the autogenerated build files. The changes I was making were to build files, not the module, things like wrapping a library in a framework for previews support. I'll grab the cquery that ibazel is using and try to see what targets it ends up running.

**Comment by cgrindel** [comment]
Did you find anything interesting from your investigation? Can we close this issue?

**Comment by joprice** [comment]
I'm not sure I'll get to this soon. I'll close and reopen if I find that it's something I can narrow down to this repo's rules.
